service: attendance-tracking-backend
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: "us-west-2"
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - rds:*
  #     Resource:
  #       - arn::aws-mysql-canvas.cqaxkdwv7tze.us-west-2.rds.amazonaws.com

functions:
  login:
    handler: src/login/login.handler
    events:
      - http:
          path: /login
          cors: true
          method: post
  fetchStudent:
    handler: src/fetchStudent/fetchStudent.handler
    events:
      - http:
          path: /student
          cors: true
          method: get
  addStudentAttendance:
    handler: src/addStudentAttendance/addStudentAttendance.handler
    events:
      - http:
          path: /addAttendance
          cors: true
          method: post
